const fs = require('fs');
const path = require('path');

const itTranslation = {
  "common": {"loading": "Caricamento...","error": "Errore","success": "Successo","cancel": "Annulla","confirm": "Conferma","delete": "Elimina","save": "Salva","edit": "Modifica","close": "Chiudi","back": "Indietro","retry": "Riprova","copied": "Copiato negli appunti","copyFailed": "Impossibile copiare il testo","selectLanguage": "Seleziona lingua","from": "Da","to": "A","translating": "Traduzione in corso...","translate": "Traduci","add": "Aggiungi","download": "Scarica","downloading": "Download in corso...","gotIt": "Capito"},
  "voice": {"title": "Voce","selectSourceLanguage": "Seleziona lingua di origine","selectTargetLanguage": "Seleziona lingua di destinazione","holdToSpeak": "Tieni premuto per parlare","listening": "Ascolto...","processing": "Elaborazione...","translationResult": "Risultato traduzione","original": "Originale","translated": "Tradotto","playOriginal": "Riproduci originale","playTranslation": "Riproduci traduzione","exportTranslation": "Esporta traduzione","noMicrophonePermission": "Nessun permesso microfono","pleaseEnableMicrophone": "Abilita il microfono nelle impostazioni"},
  "language": {"auto": "Rilevamento automatico","autoDetect": "Auto Detect","chinese": "Cinese","english": "Inglese","japanese": "Giapponese","korean": "Coreano","thai": "Tailandese","vietnamese": "Vietnamita","spanish": "Spagnolo","french": "Francese","german": "Tedesco","italian": "Italiano","portuguese": "Portoghese","russian": "Russo","arabic": "Arabo","turkish": "Turco","dutch": "Olandese","polish": "Polacco","filipino": "Filipino","zhCN": "Cinese (Semplificato)","zhTW": "Cinese (Tradizionale)","ja": "Giapponese","ko": "Coreano","en": "Inglese"},
  "history": {"title": "Cronologia","noHistory": "Nessuna cronologia traduzioni","clearHistory": "Cancella cronologia","confirmClear": "Sei sicuro di voler cancellare tutta la cronologia delle traduzioni?","deleteSuccess": "Eliminato con successo","detailTitle": "Dettagli traduzione","justNow": "Proprio ora","minutesAgo": "{{count}} minuti fa","hoursAgo": "{{count}} ore fa","daysAgo": "{{count}} giorni fa","voiceTranslation": "Traduzione vocale","textTranslation": "Traduzione testo","imageTranslation": "Traduzione immagine","languagePair": "Coppia lingue","originalText": "Testo originale","translatedText": "Testo tradotto","translationTime": "Ora traduzione","playOriginal": "Riproduci originale","playTranslation": "Riproduci traduzione"},
  "text": {"title": "Testo","inputTextForTranslation": "Inserisci testo per traduzione rapida","pasteText": "Incolla testo","clearText": "Cancella testo","inputPlaceholder": "Inserisci o incolla il testo da tradurre...","characterCount": "{{count}} caratteri","translationResult": "Risultato traduzione","originalText": "Testo originale","translatedText": "Testo tradotto","exportTXT": "Esporta TXT","exportWord": "Esporta Word","exportPDF": "Esporta PDF","selectExportContent": "Seleziona contenuto da esportare","originalOnly": "Solo originale","translatedOnly": "Solo traduzione","exportFailed": "Impossibile esportare file TXT","exportWordFailed": "Impossibile esportare file Word, riprova","exportPDFFailed": "Impossibile esportare file PDF, riprova"},
  "tabs": {"voice": "Voce","text": "Testo","camera": "Fotocamera","phrases": "Frasi"},
  "camera": {"takePhoto": "Scatta foto","retake": "Ripeti","saveOptions": "Opzioni salvataggio","saveImage": "Salva immagine","selectSaveMethod": "Seleziona metodo di salvataggio\nAl primo salvataggio verrà richiesto il permesso, premi \"Consenti\"","selectContentType": "Seleziona tipo di contenuto da salvare","originalImageOnly": "Solo immagine originale","originalImage": "Immagine originale","translatedImageOnly": "Solo immagine tradotta","translatedImage": "Immagine tradotta","saveBoth": "Salva entrambe","shareImage": "Condividi immagine","saving": "Salvataggio"},
  "phrases": {"title": "Frasi","common": "Comune","saved": "Salvato","addCategory": "Aggiungi categoria","deleteCategory": "Elimina categoria","renameCategory": "Rinomina categoria","addPhrase": "Aggiungi frase","editPhrase": "Modifica frase","deletePhrase": "Elimina frase","phrasePlaceholder": "Inserisci frase...","categoryName": "Nome categoria","categoryNamePlaceholder": "Inserisci nome categoria...","confirmDelete": "Sei sicuro di voler eliminare?","phraseSaved": "La frase è stata aggiunta alla categoria","enterKeyword": "Inserisci parola chiave","translating": "Traduzione...","fillComplete": "Compila il contenuto completo della frase","smartPhrase": "Frase intelligente","phrasesSaved": "Le frasi sono state salvate nella categoria","refreshFailed": "Aggiornamento fallito","pleaseRetry": "Riprova più tardi","travelTitle": "Viaggi e Trasporti","travelDesc": "Indicazioni, trasporti, prenotazione posti","shoppingTitle": "Shopping","shoppingDesc": "Richiesta prezzi, metodi di pagamento, prova e resi","diningTitle": "Ristorazione","diningDesc": "Ordinazioni, preferenze alimentari, informazioni allergie","emergencyTitle": "Emergenza","emergencyDesc": "Richieste di aiuto, emergenze mediche, oggetti smarriti","hotelTitle": "Alloggio","hotelDesc": "Prenotazione, servizi hotel, servizio in camera","communicationTitle": "Comunicazione quotidiana","communicationDesc": "Saluti, espressioni cortesi, consigli di conversazione","medicalTitle": "Medico e Salute","medicalDesc": "Appuntamenti medici, descrizione sintomi, necessità farmaci"},
  "settings": {"title": "Impostazioni","generalSettings": "Impostazioni generali","generalSettingsSubtitle": "Tema, lingua, riproduzione e altre impostazioni","languagePacks": "Pacchetti lingua","languagePacksSubtitle": "Gestisci pacchetti lingua offline","about": "Informazioni","aboutSubtitle": "Versione app e informazioni","theme": "Tema","themeLight": "Chiaro","themeDark": "Scuro","themeSystem": "Sistema","appLanguage": "Lingua app","appLanguageSubtitle": "Lingua di visualizzazione interfaccia","autoPlaySettings": "Impostazioni riproduzione automatica","autoPlaySubtitle": "Configura riproduzione audio automatica","version": "Versione","checkUpdate": "Verifica aggiornamenti","feedback": "Feedback","privacy": "Informativa privacy","terms": "Termini di servizio","voiceModel": "Modello vocale","voiceModelSubtitle": "Seleziona modello riconoscimento vocale","selectVoiceModel": "Seleziona modello vocale","voiceModelDescription": "I modelli più piccoli sono più veloci ma meno precisi. I modelli più grandi sono più precisi ma richiedono più risorse.","small": "Piccolo","smallDescription": "Veloce, precisione media ({{size}})","medium": "Medio","mediumDescription": "Equilibrio tra velocità e precisione ({{size}})","large": "Grande","largeDescription": "Alta precisione, velocità più lenta ({{size}})","downloadModel": "Scarica modello","downloadingModel": "Download modello...","modelDownloaded": "Modello scaricato","deleteModel": "Elimina modello","confirmDeleteModel": "Sei sicuro di voler eliminare questo modello?","modelDeleted": "Modello eliminato","downloadFailed": "Download fallito","notDownloaded": "Non scaricato","downloaded": "Scaricato","translationEngine": "Motore traduzione","translationEngineSubtitle": "Seleziona motore traduzione","selectTranslationEngine": "Seleziona motore traduzione","googleTranslate": "Google Traduttore","googleTranslateDescription": "Servizio traduzione di Google","deepl": "DeepL","deeplDescription": "Traduzione di alta qualità (richiede registrazione)","microsoftTranslator": "Microsoft Translator","microsoftTranslatorDescription": "Servizio traduzione di Microsoft","offlineTranslation": "Traduzione offline","offlineTranslationDescription": "Traduzione offline (richiede download pacchetti lingua)"},
  "errors": {"networkError": "Errore di rete, verifica la connessione","translationFailed": "Traduzione fallita","recordingFailed": "Registrazione fallita","noText": "Nessun testo","noAudio": "Nessun audio","permissionDenied": "Permesso negato","playbackFailed": "Impossibile riprodurre l'originale"},
  "autoPlay": {"title": "Impostazioni riproduzione automatica","infoTitle": "Istruzioni riproduzione automatica","infoMessage": "• Riproduci automaticamente traduzione vocale: Riproduce automaticamente il risultato dopo la traduzione vocale\n• Riproduci automaticamente traduzione testo: Legge automaticamente il risultato dopo la traduzione testo\n• Le due funzioni possono essere attivate/disattivate indipendentemente","voiceTitle": "Riproduci automaticamente traduzione vocale","voiceDescription": "Riproduce automaticamente il risultato dopo la traduzione vocale","textTitle": "Riproduci automaticamente traduzione testo","textDescription": "Legge automaticamente il risultato dopo la traduzione testo","currentStatus": "Stato attuale","statusBoth": "Verranno riprodotti i risultati di traduzione vocale e testo","statusVoiceOnly": "Verrà riprodotto il risultato di traduzione vocale","statusTextOnly": "Verrà letto il risultato di traduzione testo","statusOff": "Riproduzione automatica disattivata"},
  "languagePacks": {"title": "Gestione pacchetti lingua","downloaded": "Scaricato","notDownloaded": "Non scaricato","delete": "Elimina","download": "Scarica","storageUsed": "Archiviazione usata","downloadedCount": "Scaricati","packs": "pacchetti lingua"},
  "vosk": {"modelManagement": "Gestione modelli","modelManagementSubtitle": "Scarica e gestisci modelli riconoscimento vocale","availableModels": "Modelli disponibili","downloadedModels": "Modelli scaricati","modelSize": "Dimensione","accuracy": "Precisione","speed": "Velocità","high": "Alta","medium": "Media","low": "Bassa","fast": "Veloce","slow": "Lenta","download": "Scarica","delete": "Elimina","downloading": "Download...","downloaded": "Scaricato","confirmDelete": "Sei sicuro di voler eliminare questo modello?","deleteSuccess": "Modello eliminato con successo","deleteFailed": "Eliminazione modello fallita","downloadFailed": "Download fallito","noModels": "Nessun modello disponibile","selectModel": "Seleziona modello","currentModel": "Modello attuale","switchModel": "Cambia modello","switchSuccess": "Modello cambiato con successo","switchFailed": "Cambio modello fallito","modelNotDownloaded": "Scarica prima il modello","storageUsed": "Archiviazione usata","freeSpace": "Spazio libero","totalSpace": "Spazio totale","downloadProgress": "Progresso download"}
};

const ptTranslation = {
  "common": {"loading": "Carregando...","error": "Erro","success": "Sucesso","cancel": "Cancelar","confirm": "Confirmar","delete": "Excluir","save": "Salvar","edit": "Editar","close": "Fechar","back": "Voltar","retry": "Tentar novamente","copied": "Copiado para a área de transferência","copyFailed": "Não foi possível copiar o texto","selectLanguage": "Selecionar idioma","from": "De","to": "Para","translating": "Traduzindo...","translate": "Traduzir","add": "Adicionar","download": "Baixar","downloading": "Baixando...","gotIt": "Entendi"},
  "voice": {"title": "Voz","selectSourceLanguage": "Selecionar idioma de origem","selectTargetLanguage": "Selecionar idioma de destino","holdToSpeak": "Segure para falar","listening": "Ouvindo...","processing": "Processando...","translationResult": "Resultado da tradução","original": "Original","translated": "Traduzido","playOriginal": "Reproduzir original","playTranslation": "Reproduzir tradução","exportTranslation": "Exportar tradução","noMicrophonePermission": "Sem permissão de microfone","pleaseEnableMicrophone": "Por favor, ative o microfone nas configurações"},
  "language": {"auto": "Detecção automática","autoDetect": "Auto Detect","chinese": "Chinês","english": "Inglês","japanese": "Japonês","korean": "Coreano","thai": "Tailandês","vietnamese": "Vietnamita","spanish": "Espanhol","french": "Francês","german": "Alemão","italian": "Italiano","portuguese": "Português","russian": "Russo","arabic": "Árabe","turkish": "Turco","dutch": "Holandês","polish": "Polonês","filipino": "Filipino","zhCN": "Chinês (Simplificado)","zhTW": "Chinês (Tradicional)","ja": "Japonês","ko": "Coreano","en": "Inglês"},
  "history": {"title": "Histórico","noHistory": "Sem histórico de tradução","clearHistory": "Limpar histórico","confirmClear": "Tem certeza de que deseja limpar todo o histórico de tradução?","deleteSuccess": "Excluído com sucesso","detailTitle": "Detalhes da tradução","justNow": "Agora mesmo","minutesAgo": "{{count}} minutos atrás","hoursAgo": "{{count}} horas atrás","daysAgo": "{{count}} dias atrás","voiceTranslation": "Tradução de voz","textTranslation": "Tradução de texto","imageTranslation": "Tradução de imagem","languagePair": "Par de idiomas","originalText": "Texto original","translatedText": "Texto traduzido","translationTime": "Hora da tradução","playOriginal": "Reproduzir original","playTranslation": "Reproduzir tradução"},
  "text": {"title": "Texto","inputTextForTranslation": "Digite texto para tradução rápida","pasteText": "Colar texto","clearText": "Limpar texto","inputPlaceholder": "Digite ou cole o texto a traduzir...","characterCount": "{{count}} caracteres","translationResult": "Resultado da tradução","originalText": "Texto original","translatedText": "Texto traduzido","exportTXT": "Exportar TXT","exportWord": "Exportar Word","exportPDF": "Exportar PDF","selectExportContent": "Selecionar conteúdo a exportar","originalOnly": "Apenas original","translatedOnly": "Apenas tradução","exportFailed": "Não foi possível exportar o arquivo TXT","exportWordFailed": "Não foi possível exportar o arquivo Word, tente novamente","exportPDFFailed": "Não foi possível exportar o arquivo PDF, tente novamente"},
  "tabs": {"voice": "Voz","text": "Texto","camera": "Câmera","phrases": "Frases"},
  "camera": {"takePhoto": "Tirar foto","retake": "Repetir","saveOptions": "Opções de salvamento","saveImage": "Salvar imagem","selectSaveMethod": "Selecionar método de salvamento\nNa primeira vez será solicitada permissão, pressione \"Permitir\"","selectContentType": "Selecionar tipo de conteúdo a salvar","originalImageOnly": "Apenas imagem original","originalImage": "Imagem original","translatedImageOnly": "Apenas imagem traduzida","translatedImage": "Imagem traduzida","saveBoth": "Salvar ambas","shareImage": "Compartilhar imagem","saving": "Salvando"},
  "phrases": {"title": "Frases","common": "Comum","saved": "Salvo","addCategory": "Adicionar categoria","deleteCategory": "Excluir categoria","renameCategory": "Renomear categoria","addPhrase": "Adicionar frase","editPhrase": "Editar frase","deletePhrase": "Excluir frase","phrasePlaceholder": "Digite frase...","categoryName": "Nome da categoria","categoryNamePlaceholder": "Digite nome da categoria...","confirmDelete": "Tem certeza de que deseja excluir?","phraseSaved": "A frase foi adicionada à categoria","enterKeyword": "Digite palavra-chave","translating": "Traduzindo...","fillComplete": "Por favor, preencha o conteúdo completo da frase","smartPhrase": "Frase inteligente","phrasesSaved": "As frases foram salvas na categoria","refreshFailed": "Atualização falhou","pleaseRetry": "Por favor, tente novamente mais tarde","travelTitle": "Viagens e Transporte","travelDesc": "Direções, transporte, reserva de assentos","shoppingTitle": "Compras","shoppingDesc": "Consulta de preços, métodos de pagamento, experimentar e devoluções","diningTitle": "Alimentação","diningDesc": "Pedidos, preferências alimentares, informações sobre alergias","emergencyTitle": "Emergência","emergencyDesc": "Pedidos de ajuda, emergências médicas, objetos perdidos","hotelTitle": "Acomodação","hotelDesc": "Reserva, instalações do hotel, serviço de quarto","communicationTitle": "Comunicação diária","communicationDesc": "Cumprimentos, expressões educadas, dicas de conversa","medicalTitle": "Médico e Saúde","medicalDesc": "Consultas médicas, descrição de sintomas, necessidades de medicamentos"},
  "settings": {"title": "Configurações","generalSettings": "Configurações gerais","generalSettingsSubtitle": "Tema, idioma, reprodução e outras configurações","languagePacks": "Pacotes de idioma","languagePacksSubtitle": "Gerenciar pacotes de idioma offline","about": "Sobre","aboutSubtitle": "Versão do aplicativo e informações","theme": "Tema","themeLight": "Claro","themeDark": "Escuro","themeSystem": "Sistema","appLanguage": "Idioma do aplicativo","appLanguageSubtitle": "Idioma de exibição da interface","autoPlaySettings": "Configurações de reprodução automática","autoPlaySubtitle": "Configurar reprodução de áudio automática","version": "Versão","checkUpdate": "Verificar atualização","feedback": "Feedback","privacy": "Política de privacidade","terms": "Termos de serviço","voiceModel": "Modelo de voz","voiceModelSubtitle": "Selecionar modelo de reconhecimento de voz","selectVoiceModel": "Selecionar modelo de voz","voiceModelDescription": "Modelos menores são mais rápidos, mas menos precisos. Modelos maiores são mais precisos, mas exigem mais recursos.","small": "Pequeno","smallDescription": "Rápido, precisão média ({{size}})","medium": "Médio","mediumDescription": "Equilíbrio entre velocidade e precisão ({{size}})","large": "Grande","largeDescription": "Alta precisão, velocidade mais lenta ({{size}})","downloadModel": "Baixar modelo","downloadingModel": "Baixando modelo...","modelDownloaded": "Modelo baixado","deleteModel": "Excluir modelo","confirmDeleteModel": "Tem certeza de que deseja excluir este modelo?","modelDeleted": "Modelo excluído","downloadFailed": "Download falhou","notDownloaded": "Não baixado","downloaded": "Baixado","translationEngine": "Motor de tradução","translationEngineSubtitle": "Selecionar motor de tradução","selectTranslationEngine": "Selecionar motor de tradução","googleTranslate": "Google Tradutor","googleTranslateDescription": "Serviço de tradução do Google","deepl": "DeepL","deeplDescription": "Tradução de alta qualidade (requer registro)","microsoftTranslator": "Microsoft Translator","microsoftTranslatorDescription": "Serviço de tradução da Microsoft","offlineTranslation": "Tradução offline","offlineTranslationDescription": "Tradução offline (requer download de pacotes de idioma)"},
  "errors": {"networkError": "Erro de rede, verifique a conexão","translationFailed": "Tradução falhou","recordingFailed": "Gravação falhou","noText": "Sem texto","noAudio": "Sem áudio","permissionDenied": "Permissão negada","playbackFailed": "Não foi possível reproduzir o original"},
  "autoPlay": {"title": "Configurações de reprodução automática","infoTitle": "Instruções de reprodução automática","infoMessage": "• Reproduzir automaticamente tradução de voz: Reproduz automaticamente o resultado após a tradução de voz\n• Reproduzir automaticamente tradução de texto: Lê automaticamente o resultado após a tradução de texto\n• As duas funções podem ser ativadas/desativadas independentemente","voiceTitle": "Reproduzir automaticamente tradução de voz","voiceDescription": "Reproduz automaticamente o resultado após a tradução de voz","textTitle": "Reproduzir automaticamente tradução de texto","textDescription": "Lê automaticamente o resultado após a tradução de texto","currentStatus": "Status atual","statusBoth": "Reproduzirá os resultados de tradução de voz e texto","statusVoiceOnly": "Reproduzirá o resultado de tradução de voz","statusTextOnly": "Lerá o resultado de tradução de texto","statusOff": "Reprodução automática desativada"},
  "languagePacks": {"title": "Gerenciamento de pacotes de idioma","downloaded": "Baixado","notDownloaded": "Não baixado","delete": "Excluir","download": "Baixar","storageUsed": "Armazenamento usado","downloadedCount": "Baixados","packs": "pacotes de idioma"},
  "vosk": {"modelManagement": "Gerenciamento de modelos","modelManagementSubtitle": "Baixar e gerenciar modelos de reconhecimento de voz","availableModels": "Modelos disponíveis","downloadedModels": "Modelos baixados","modelSize": "Tamanho","accuracy": "Precisão","speed": "Velocidade","high": "Alta","medium": "Média","low": "Baixa","fast": "Rápida","slow": "Lenta","download": "Baixar","delete": "Excluir","downloading": "Baixando...","downloaded": "Baixado","confirmDelete": "Tem certeza de que deseja excluir este modelo?","deleteSuccess": "Modelo excluído com sucesso","deleteFailed": "Falha ao excluir modelo","downloadFailed": "Download falhou","noModels": "Nenhum modelo disponível","selectModel": "Selecionar modelo","currentModel": "Modelo atual","switchModel": "Mudar modelo","switchSuccess": "Modelo alterado com sucesso","switchFailed": "Falha ao mudar modelo","modelNotDownloaded": "Por favor, baixe o modelo primeiro","storageUsed": "Armazenamento usado","freeSpace": "Espaço livre","totalSpace": "Espaço total","downloadProgress": "Progresso do download"}
};

// 保存it和pt
fs.writeFileSync(path.join(__dirname, '..', 'locales', 'it.json'), JSON.stringify(itTranslation, null, 2) + '\n', 'utf8');
fs.writeFileSync(path.join(__dirname, '..', 'locales', 'pt.json'), JSON.stringify(ptTranslation, null, 2) + '\n', 'utf8');

console.log('✓ Restored it.json with complete translation');
console.log('✓ Restored pt.json with complete translation');
console.log('\n✅ Italian and Portuguese restored!');

